-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjky1GVvqxsA3K/x4
8w40JyjAu3ki9IYaMcTPmYKrz+SgCgYIKoZIzj0DAQehRANCAATZW15FUxNcx2IS
1UUaLSg9Qmur5E1YJqm+khg5FT/UTtUf5ka7pqvn/lKqBl5GATUXmJUcQQv3WmTe
MyxEhUbX
-----END PRIVATE KEY-----